version: '3.1'

networks:
  wulkanizator-ddd:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container-ddd
    ports:
      - "15600:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - wulkanizator-ddd

  php:
    build:
      context: ./php
    container_name: php-container-ddd
#    ports:
#      - "15610:9000"
    volumes:
      - ./app:/var/www/project
    environment:
      XDEBUG_MODE: coverage
    networks:
      - wulkanizator-ddd

  postgres:
    image: postgres:13
    container_name: postgres-container-ddd
    ports:
      - "15620:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: wulkanizator-ddd
      POSTGRES_USER: wulkanizator_user
      POSTGRES_PASSWORD: Np51cvRi13o
    networks:
      - wulkanizator-ddd
    
  mailhog:
    image: mailhog/mailhog
    container_name: wulkan2mailhog-ddd
    ports:
    - "8025:8025"
    - "1025:1025"
    networks:
      - wulkanizator-ddd